// <auto-generated />
using System;
using Book_EF.EntityModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_EF.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20240505074449_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Book_EF.EntityModels.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("author_name");

                    b.HasKey("Id");

                    b.ToTable("author", (string)null);
                });

            modelBuilder.Entity("Book_EF.EntityModels.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("author_id");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("char(36)")
                        .HasColumnName("class_id");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_delete");

                    b.Property<bool>("IsRecommend")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recommend");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int(11)")
                        .HasColumnName("page_count");

                    b.Property<string>("PublishYear")
                        .HasColumnType("char(4)")
                        .HasColumnName("publish_year");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("char(36)")
                        .HasColumnName("publisher_id");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("book", (string)null);
                });

            modelBuilder.Entity("Book_EF.EntityModels.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("Book_EF.EntityModels.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("PublisherName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("publisher", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
