name: Deploy Book Lambda Stack

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: BookLambda
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_COGNITO_USER_POOL_ID: ${{ secrets.AWS_COGNITO_USER_POOL_ID }}
      BASTION_HOST: ${{ secrets.BASTION_HOST }}
      BASTION_USER: ${{ secrets.BASTION_USER }}
      BASTION_SSH_KEY: ${{ secrets.BASTION_SSH_KEY }}
      POSTGRE_DATABASE_PORT: ${{ secrets.POSTGRE_DATABASE_PORT }}
      DEFAULT_CONNECTION_STRING: ${{ secrets.DEFAULT_CONNECTION_STRING }}
      AWS_COGNITO_USER_POOL_CLIENT_ID: ${{ secrets.AWS_COGNITO_USER_POOL_CLIENT_ID }}
      AWS_COGNITO_USER_POOL_CLIENT_SECRET: ${{ secrets.AWS_COGNITO_USER_POOL_CLIENT_SECRET }}
      AWS_COGNITO_USER_POOL_DOMAIN: ${{ secrets.AWS_COGNITO_USER_POOL_DOMAIN }}
      AWS_COGNITO_REDIRECT_URI: ${{ secrets.AWS_COGNITO_REDIRECT_URI }}
      SIGNIN_SUCCESS_REDIRECT_URI: ${{ secrets.SIGNIN_SUCCESS_REDIRECT_URI }}
      AUTH_FAIL_REDIRECT_URI: ${{ secrets.AUTH_FAIL_REDIRECT_URI }}
      COOKIE_DOMAIN: ${{ secrets.COOKIE_DOMAIN }}
      ConnectionStrings__DefaultConnection: ${{ secrets.DEFAULT_CONNECTION_STRING }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install CDK
        run: npm install -g aws-cdk

      # - name: Install dotnet ef tool
      #   run: |
      #     dotnet restore
      #     dotnet tool install --global dotnet-ef

      # - name: Migration
      #   run: |
      #     mkdir ~/.ssh
      #     ssh-keyscan -H $BASTION_HOST >> ~/.ssh/known_hosts
      #     eval `ssh-agent -s`
      #     ssh-add - <<< "$BASTION_SSH_KEY"
      #     ssh -fN -v -L $POSTGRE_DATABASE_PORT:$POSTGRES_DATABASE_HOST:$POSTGRE_DATABASE_PORT $BASTION_USER@$BASTION_HOST
      #     dotnet ef database update --project Book_Lambda/src/Book_Lambda.csproj

      - name: Publish .NET application
        run: |
          dotnet publish -c Release -r linux-x64

      - name: Deploy CDK Stack
        run: |
          cd aws-cdk && cdk deploy --require-approval never
